services:
  postgres:
    image: 'postgres:17'
    container_name: bankcardmanager-postgres-1
    environment:
      POSTGRES_DB: bank_cards
      POSTGRES_USER: bankcard_user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bankcard_user -d bank_cards"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: